### ISSUE TITLE
APPSDIR not defined

### ISSUE THREAD

**Issue by brimstone** [SpaceApi-archive/OpenSpaceLint#95]
1. index.php doesn't check for APPSDIR to be defined. It could be not checking much more.
2. APPSDIR is not defined in the sample config.

**Comment by brimstone** [comment]
I'm modifying the repo on SpaceApi/OpenSpaceLint instead.

**Comment by slopjong** [comment]
That's totally fine, I mean that you modify the other repo. Thanks for the notice :-)
